---

# Based on instructions at:
# http://www.mono-project.com/download/#download-lin-centos

- name: Check if Mono repo is already configured.
  stat:
    path: "{{ mono_repofile_path }}"
  register: mono_repofile_result

- name: Install Mono repo.
  yum_repository:
    name: "download.mono-project.com_repo_centos{{ ansible_distribution_major_version }}_"
    description: "added from: http://download.mono-project.com/repo/centos{{ ansible_distribution_major_version }}/"
    baseurl: "{{ mono_base_url }}"
    gpgkey: "{{ mono_repo_gpg_key_url }}"
    gpgcheck: yes
    enabled: yes
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not mono_repofile_result.stat.exists
