---

# Based on instructions at:
# http://www.mono-project.com/download/#download-lin-centos

- name: Check if Mono repo is already configured.
  stat:
    path: "{{ mono_repofile_path }}"
  register: mono_repofile_result

- name: Add Mono RPM key.
  rpm_key:
    key: "{{ mono_rpm_key_url }}"
    state: present

- name: Install Mono repo.
  yum_repository:
    name: "mono-centos{{ ansible_distribution_major_version }}-stable"
    description: "mono-centos{{ ansible_distribution_major_version }}-stable"
    baseurl: "{{ mono_base_url }}"
    gpgkey: "{{ mono_repo_gpg_key_url }}"
    gpgcheck: yes
    enabled: yes
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not mono_repofile_result.stat.exists
